const express = require('express')
const controller = require('../controller/controller')
const router = express.Router()
const {authenticateJWT,generateToken} = require('../middleware/auth')
router.post('/login',generateToken)
router.post('/register',controller.postRegister)
router.get('/get-task-data',authenticateJWT,controller.getTaskData)
router.post('/post-task-data',authenticateJWT,controller.postTaskData)
router.post('/put-task-data',authenticateJWT,controller.putTaskData)
router.delete('/delete-task-data',authenticateJWT,controller.deleteTaskData)
module.exports = router